#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_powermenu.xyz"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
run_eww() {
  eww open-many sys_side
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	eww close sys_side
	rm "$FILE"
fi

