#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          12
bspc config top_padding         35

bspc config normal_border_color "#444444"
bspc config focused_border_color "#999999"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a discord desktop='^2'
bspc rule -a Eog state=floating center=true
bspc rule -a Xfce4-terminal state=floating center=true
bspc rule -a JanrexClient state=floating center=true
bspc rule -a Shutter state=floating center=true
bspc rule -a Org.gnome.Nautilus state=floating center=true
bspc rule -a Gnome-calculator state=floating center=true
bspc rule -a Pick-colour-picker state=floating center=true
bspc rule -a mpv state=floating center=true

xrandr --output LVDS1 --brightness 1 &

# /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
xfsettingsd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom &
nitrogen --set-scaled ~/Pictures/Wallpaper/gradientwave.png
/home/keval/scripts/ewwstartup.sh &
